const RESPONSE_CODE = {
    DB_ERROR: "DB_ERROR",
    PROCESS_ERROR: "PROCESS_ERROR",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    BASIC_SUCCESS: "BASIC_SUCCESS",
    SUCCESS: "SUCCESS",
    REQ_VALID_ERROR: "REQ_VALID_ERROR",
};

module.exports = RESPONSE_CODE