var RESPONSE_CODES = Object.freeze({
    P_ERROR__FORBIDDEN: "P_ERROR_F",
    P_ERROR__NOT_FOUND: "P_ERROR_NF",
    P_ERROR__UNAUTHORIZED: "P_ERROR_UNAUTHORIZED",
    S_ERROR_INTERNAL: "S_ERROR_INTERNAL",
    REQ_VALID_ERROR: "REQ_VALID_ERROR",
    DB_ERROR: "DB_ERROR",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    BASIC_SUCCESS: "BASIC_SUCCESS",
    BASIC_SUCCESS__CREATED: "BASIC_SUCCESS_CREATED",
    SUCCESS: "SUCCESS",
    SUCCESS__CREATED: "SUCCESS_C",
});

module.exports = RESPONSE_CODES;